# netlify.toml
[build]
  command = "npm ci && npm run build"
  publish = "client/dist"   # adjust to "dist" if your Vite outDir is root/dist

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
