[build]
  command = "npm ci && npx vite build --config vite.config.ts"
  publish = "client/dist"

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
