[build]
  command = "npm ci && npm run build"
  publish = "client/dist"

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200


[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
